module.exports = [
  {
    listingTitle: "Condo in Manhattan",
    location: {
      city: "New York",
      state: "NY",
      longitude: -73.935242,
      latitude: 40.73061,
    },
    pricePerNight: 250,
    bedrooms: 2,
    bathrooms: 2,
    description:
      "Modern condo with stunning city views, close to central park.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Beach House in Malibu",
    location: {
      city: "Malibu",
      state: "CA",
      longitude: -118.799623,
      latitude: 34.025921,
    },
    pricePerNight: 450,
    bedrooms: 4,
    bathrooms: 3,
    description: "Spacious beach house with private access to the beach.",
    propertyType: "house",
  },
  {
    listingTitle: "Penthouse in Miami",
    location: {
      city: "Miami",
      state: "FL",
      longitude: -80.19179,
      latitude: 25.76168,
    },
    pricePerNight: 600,
    bedrooms: 3,
    bathrooms: 2,
    description: "Luxurious penthouse with ocean views and private pool.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Loft in Downtown Seattle",
    location: {
      city: "Seattle",
      state: "WA",
      longitude: -122.335167,
      latitude: 47.608013,
    },
    pricePerNight: 220,
    bedrooms: 1,
    bathrooms: 1,
    description: "Modern loft with industrial design, close to attractions.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Hotel Suite in Chicago",
    location: {
      city: "Chicago",
      state: "IL",
      longitude: -87.623177,
      latitude: 41.881832,
    },
    pricePerNight: 270,
    bedrooms: 1,
    bathrooms: 1,
    description: "Elegant hotel suite with lake views and top amenities.",
    propertyType: "hotel",
  },
  {
    listingTitle: "Apartment in Boston",
    location: {
      city: "Boston",
      state: "MA",
      longitude: -71.05888,
      latitude: 42.360082,
    },
    pricePerNight: 230,
    bedrooms: 2,
    bathrooms: 1,
    description: "Historic apartment with modern upgrades, near downtown.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Modern Loft in Austin",
    location: {
      city: "Austin",
      state: "TX",
      longitude: -97.743057,
      latitude: 30.267153,
    },
    pricePerNight: 210,
    bedrooms: 1,
    bathrooms: 1,
    description: "Stylish loft in downtown Austin with great city views.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Villa in Orlando",
    location: {
      city: "Orlando",
      state: "FL",
      longitude: -81.379234,
      latitude: 28.538336,
    },
    pricePerNight: 320,
    bedrooms: 4,
    bathrooms: 3,
    description:
      "Spacious villa with private pool, perfect for family vacations.",
    propertyType: "house",
  },
  {
    listingTitle: "Eco-friendly Tiny House",
    location: {
      city: "Portland",
      state: "OR",
      longitude: -122.676483,
      latitude: 45.523064,
    },
    pricePerNight: 140,
    bedrooms: 1,
    bathrooms: 1,
    description: "Cozy and eco-friendly tiny house in a serene neighborhood.",
    propertyType: "house",
  },
  {
    listingTitle: "Historic Apartment in Charleston",
    location: {
      city: "Charleston",
      state: "SC",
      longitude: -79.931053,
      latitude: 32.776474,
    },
    pricePerNight: 200,
    bedrooms: 2,
    bathrooms: 2,
    description: "Beautiful historic apartment with modern amenities.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Mountain Lodge in Lake Tahoe",
    location: {
      city: "Lake Tahoe",
      state: "CA",
      longitude: -120.032349,
      latitude: 39.096848,
    },
    pricePerNight: 400,
    bedrooms: 3,
    bathrooms: 3,
    description: "Charming mountain lodge with stunning lake views.",
    propertyType: "house",
  },
  {
    listingTitle: "Downtown Condo in Denver",
    location: {
      city: "Denver",
      state: "CO",
      longitude: -104.99025,
      latitude: 39.739235,
    },
    pricePerNight: 230,
    bedrooms: 2,
    bathrooms: 2,
    description: "Modern downtown condo with great city skyline views.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Cozy Bungalow in Santa Fe",
    location: {
      city: "Santa Fe",
      state: "NM",
      longitude: -105.937799,
      latitude: 35.686975,
    },
    pricePerNight: 190,
    bedrooms: 2,
    bathrooms: 1,
    description: "Charming bungalow with artistic decor, near downtown.",
    propertyType: "house",
  },
  {
    listingTitle: "Cottage in the Berkshires",
    location: {
      city: "Great Barrington",
      state: "MA",
      longitude: -73.36254,
      latitude: 42.195979,
    },
    pricePerNight: 220,
    bedrooms: 3,
    bathrooms: 2,
    description:
      "Quaint cottage surrounded by nature, perfect for a relaxing retreat.",
    propertyType: "house",
  },
  {
    listingTitle: "Skyline Penthouse in Chicago",
    location: {
      city: "Chicago",
      state: "IL",
      longitude: -87.623177,
      latitude: 41.881832,
    },
    pricePerNight: 650,
    bedrooms: 4,
    bathrooms: 3,
    description:
      "Luxurious penthouse with panoramic city views and modern amenities.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Urban Apartment in Brooklyn",
    location: {
      city: "Brooklyn",
      state: "NY",
      longitude: -73.944158,
      latitude: 40.678178,
    },
    pricePerNight: 200,
    bedrooms: 2,
    bathrooms: 1,
    description: "Chic urban apartment located in a vibrant neighborhood.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Downtown Apartment in Nashville",
    location: {
      city: "Nashville",
      state: "TN",
      longitude: -86.781602,
      latitude: 36.162664,
    },
    pricePerNight: 250,
    bedrooms: 2,
    bathrooms: 2,
    description: "Modern apartment in the heart of downtown Nashville.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Historic Loft in New Orleans",
    location: {
      city: "New Orleans",
      state: "LA",
      longitude: -90.071533,
      latitude: 29.951065,
    },
    pricePerNight: 230,
    bedrooms: 1,
    bathrooms: 1,
    description:
      "Stylish loft in a historic building, close to French Quarter.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Modern Suite in San Diego",
    location: {
      city: "San Diego",
      state: "CA",
      longitude: -117.161084,
      latitude: 32.715738,
    },
    pricePerNight: 260,
    bedrooms: 1,
    bathrooms: 1,
    description:
      "Contemporary hotel suite with ocean views and luxurious amenities.",
    propertyType: "hotel",
  },
  {
    listingTitle: "Cozy Studio in Portland",
    location: {
      city: "Portland",
      state: "OR",
      longitude: -122.676207,
      latitude: 45.523451,
    },
    pricePerNight: 120,
    bedrooms: 1,
    bathrooms: 1,
    description: "Compact and cozy studio in the heart of Portland.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Budget-Friendly Room in Orlando",
    location: {
      city: "Orlando",
      state: "FL",
      longitude: -81.379234,
      latitude: 28.538336,
    },
    pricePerNight: 90,
    bedrooms: 1,
    bathrooms: 1,
    description:
      "Affordable private room with shared amenities, near theme parks.",
    propertyType: "hotel",
  },
  {
    listingTitle: "Historic House in Savannah",
    location: {
      city: "Savannah",
      state: "GA",
      longitude: -81.099834,
      latitude: 32.083541,
    },
    pricePerNight: 180,
    bedrooms: 3,
    bathrooms: 2,
    description:
      "Beautiful historic house with modern updates in downtown Savannah.",
    propertyType: "house",
  },
  {
    listingTitle: "Economical Loft in Philadelphia",
    location: {
      city: "Philadelphia",
      state: "PA",
      longitude: -75.165222,
      latitude: 39.952583,
    },
    pricePerNight: 130,
    bedrooms: 1,
    bathrooms: 1,
    description: "Economical loft in a prime location, close to attractions.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Modern Apartment in Minneapolis",
    location: {
      city: "Minneapolis",
      state: "MN",
      longitude: -93.265015,
      latitude: 44.977753,
    },
    pricePerNight: 160,
    bedrooms: 2,
    bathrooms: 1,
    description: "Modern apartment with stylish decor in downtown Minneapolis.",
    propertyType: "apartment",
  },

  {
    listingTitle: "Stylish Apartment in Manhattan",
    location: {
      city: "New York",
      state: "NY",
      longitude: -73.98513,
      latitude: 40.758896,
    },
    pricePerNight: 300,
    bedrooms: 1,
    bathrooms: 1,
    description: "Modern and stylish apartment in the heart of Manhattan.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Luxury Condo in Los Angeles",
    location: {
      city: "Los Angeles",
      state: "CA",
      longitude: -118.243683,
      latitude: 34.052235,
    },
    pricePerNight: 350,
    bedrooms: 2,
    bathrooms: 2,
    description: "Luxurious condo with city views and high-end amenities.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Modern Loft in San Francisco",
    location: {
      city: "San Francisco",
      state: "CA",
      longitude: -122.419416,
      latitude: 37.774929,
    },
    pricePerNight: 280,
    bedrooms: 1,
    bathrooms: 1,
    description: "Spacious loft with industrial design in a prime location.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Urban Apartment in Seattle",
    location: {
      city: "Seattle",
      state: "WA",
      longitude: -122.332071,
      latitude: 47.606209,
    },
    pricePerNight: 230,
    bedrooms: 1,
    bathrooms: 1,
    description:
      "Contemporary apartment with stunning city views and modern amenities.",
    propertyType: "apartment",
  },
  {
    listingTitle: "City Center Apartment in Boston",
    location: {
      city: "Boston",
      state: "MA",
      longitude: -71.05888,
      latitude: 42.360082,
    },
    pricePerNight: 260,
    bedrooms: 2,
    bathrooms: 1,
    description: "Chic apartment in the city center, close to historic sites.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Downtown Apartment in Austin",
    location: {
      city: "Austin",
      state: "TX",
      longitude: -97.743057,
      latitude: 30.267153,
    },
    pricePerNight: 220,
    bedrooms: 1,
    bathrooms: 1,
    description: "Trendy downtown apartment with easy access to nightlife.",
    propertyType: "apartment",
  },

  {
    listingTitle: "Designer Loft in Denver",
    location: {
      city: "Denver",
      state: "CO",
      longitude: -104.99025,
      latitude: 39.739235,
    },
    pricePerNight: 210,
    bedrooms: 1,
    bathrooms: 1,
    description:
      "Designer loft with contemporary decor in the heart of downtown.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Luxury Apartment in Chicago",
    location: {
      city: "Chicago",
      state: "IL",
      longitude: -87.623177,
      latitude: 41.881832,
    },
    pricePerNight: 320,
    bedrooms: 2,
    bathrooms: 2,
    description: "Elegant apartment with lake views and upscale amenities.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Modern Studio in Washington D.C.",
    location: {
      city: "Washington",
      state: "DC",
      longitude: -77.03687,
      latitude: 38.907192,
    },
    pricePerNight: 200,
    bedrooms: 1,
    bathrooms: 1,
    description:
      "Modern studio with convenient access to government buildings and museums.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Trendy Loft in Brooklyn",
    location: {
      city: "Brooklyn",
      state: "NY",
      longitude: -73.944158,
      latitude: 40.678178,
    },
    pricePerNight: 240,
    bedrooms: 2,
    bathrooms: 1,
    description:
      "Trendy loft in a vibrant neighborhood, close to parks and cafes.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Luxury Apartment in Dallas",
    location: {
      city: "Dallas",
      state: "TX",
      longitude: -96.796856,
      latitude: 32.776664,
    },
    pricePerNight: 280,
    bedrooms: 2,
    bathrooms: 2,
    description:
      "Luxury apartment with city views and modern amenities in downtown Dallas.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Contemporary Studio in San Diego",
    location: {
      city: "San Diego",
      state: "CA",
      longitude: -117.161084,
      latitude: 32.715738,
    },
    pricePerNight: 210,
    bedrooms: 1,
    bathrooms: 1,
    description:
      "Contemporary studio with ocean views and close to attractions.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Downtown Apartment in Atlanta",
    location: {
      city: "Atlanta",
      state: "GA",
      longitude: -84.388229,
      latitude: 33.749,
    },
    pricePerNight: 200,
    bedrooms: 1,
    bathrooms: 1,
    description:
      "Downtown apartment with modern design and easy access to nightlife.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Chic Apartment in Houston",
    location: {
      city: "Houston",
      state: "TX",
      longitude: -95.369804,
      latitude: 29.760427,
    },
    pricePerNight: 220,
    bedrooms: 2,
    bathrooms: 1,
    description:
      "Chic apartment in a vibrant neighborhood with great amenities.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Urban Loft in Philadelphia",
    location: {
      city: "Philadelphia",
      state: "PA",
      longitude: -75.165222,
      latitude: 39.952583,
    },
    pricePerNight: 230,
    bedrooms: 2,
    bathrooms: 1,
    description:
      "Urban loft with industrial design and a great view of the skyline.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Modern Apartment in San Antonio",
    location: {
      city: "San Antonio",
      state: "TX",
      longitude: -98.493629,
      latitude: 29.424122,
    },
    pricePerNight: 190,
    bedrooms: 1,
    bathrooms: 1,
    description: "Modern apartment near the River Walk with great amenities.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Spacious Condo in Phoenix",
    location: {
      city: "Phoenix",
      state: "AZ",
      longitude: -112.074036,
      latitude: 33.448376,
    },
    pricePerNight: 220,
    bedrooms: 2,
    bathrooms: 2,
    description: "Spacious condo with a pool and stunning city views.",
    propertyType: "apartment",
  },
  {
    listingTitle: "Central Apartment in Portland",
    location: {
      city: "Portland",
      state: "OR",
      longitude: -122.676207,
      latitude: 45.523451,
    },
    pricePerNight: 210,
    bedrooms: 2,
    bathrooms: 1,
    description:
      "Central apartment with modern decor and close to popular spots.",
    propertyType: "apartment",
  },
];
